
name: Publish

on: 
  push:
    tags:
      - 'v**'

jobs:     
  publish: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies 📦
        run: yarn
      - name: Build library 🔧
        run: yarn build:lib
      - name: Publish package to registry 🚀
        run: npm publish
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} 